#!/usr/bin/env node
/**
 * Data audit: validates data/ephs-course-guide-2026-27.json and writes
 * docs/DATA_AUDIT.md. Run with: npm run data:audit
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = process.cwd();
const dataFile = path.join(root, "data", "ephs-course-guide-2026-27.json");
const outFile = path.join(root, "docs", "DATA_AUDIT.md");

const raw = fs.readFileSync(dataFile);
const d = JSON.parse(raw.toString("utf8"));
const fileSha = crypto.createHash("sha256").update(raw).digest("hex");

const errors = [];
const requireField = (cond, msg) => {
  if (!cond) errors.push(msg);
};

requireField(typeof d.schema_version === "string", "schema_version missing");
requireField(Array.isArray(d.courses) && d.courses.length > 0, "courses missing");
requireField(Array.isArray(d.pathways) && d.pathways.length === 5, "expected 5 pathways");
requireField(Array.isArray(d.source_pages), "source_pages missing");
requireField(d.graduation_rules?.class_of_2027, "class_of_2027 rules missing");
requireField(d.graduation_rules?.class_of_2028_and_beyond, "class_of_2028_and_beyond rules missing");

const maxPage = d.generated_from.page_count;
const missingDesc = [];
const missingGrades = [];
const missingCredits = [];
const conflicts = [];
const crossListed = [];
const invalidPages = [];
const flagCounts = { ap: 0, honors: 0, capstone: 0, skinny: 0, cis: 0, new_course: 0, college_credit: 0 };
const departments = new Set();
const ids = new Set();
const duplicateIds = [];

for (const c of d.courses) {
  // Duplicate slugs are a known source anomaly (distinct courses that
  // normalize to the same id). The app disambiguates them at load time and
  // preserves both, so this is a reported data-quality finding, not a fatal
  // schema error.
  if (ids.has(c.id)) duplicateIds.push(c.id);
  ids.add(c.id);
  for (const dep of c.departments) departments.add(dep);
  if (!c.description) missingDesc.push(c.id);
  if (!c.grades_allowed?.length) missingGrades.push(c.id);
  if (!c.credits_raw) missingCredits.push(c.id);
  if (c.data_quality?.requires_counselor_verification || c.data_quality?.conflicts_detected?.length) {
    conflicts.push(c.id);
  }
  if (c.source_appearances.length > 1) crossListed.push(c.id);
  for (const p of c.source_pages) {
    if (p < 1 || p > maxPage) invalidPages.push(`${c.id}: page ${p}`);
  }
  for (const key of ["ap", "honors", "capstone", "skinny", "cis", "new_course"]) {
    if (c.flags[key]) flagCounts[key] += 1;
  }
  if (c.college_credit_available) flagCounts.college_credit += 1;
}

const unresolved = d.pathways.map((p) => ({
  name: p.name,
  count: p.unresolved_or_external_course_names.length,
  names: p.unresolved_or_external_course_names,
}));

const list = (arr) => (arr.length === 0 ? "_None — clean._" : arr.map((x) => `- \`${x}\``).join("\n"));

const md = `# Data Audit — EPHS Course Guide 2026-27

_Generated by \`npm run data:audit\`. Re-run after replacing the dataset._

## Dataset identity

| Field | Value |
| --- | --- |
| Dataset id | \`${d.dataset_id}\` |
| Schema version | \`${d.schema_version}\` |
| Source document | ${d.generated_from.filename} (${maxPage} pages) |
| Source PDF SHA-256 | \`${d.generated_from.pdf_sha256}\` |
| Dataset file SHA-256 | \`${fileSha}\` |

## Counts

| Metric | Value |
| --- | --- |
| Structured courses | ${d.courses.length} |
| Source appearances | ${d.course_appearances.length} |
| Departments | ${departments.size} |
| Pathways | ${d.pathways.length} |
| AP courses | ${flagCounts.ap} |
| Honors courses | ${flagCounts.honors} |
| Capstone courses | ${flagCounts.capstone} |
| Skinny courses | ${flagCounts.skinny} |
| CIS courses | ${flagCounts.cis} |
| New courses | ${flagCounts.new_course} |
| College-credit courses | ${flagCounts.college_credit} |
| Cross-listed courses (multiple appearances) | ${crossListed.length} |

## Validation results

${errors.length === 0 ? "Schema validation passed." : `**Schema problems:**\n${list(errors)}`}

### Courses missing descriptions (${missingDesc.length})
${list(missingDesc)}

### Courses missing grade data (${missingGrades.length})
${list(missingGrades)}

### Courses missing credit data (${missingCredits.length})
${list(missingCredits)}

### Courses flagged with source conflicts (${conflicts.length})
${list(conflicts)}

### Invalid source-page references (${invalidPages.length})
${list(invalidPages)}

### Duplicate course slugs — distinct courses sharing an id (${duplicateIds.length})

Preserved and disambiguated at load time (never merged or dropped).

${list(duplicateIds)}

### Cross-listed courses — all appearances preserved (${crossListed.length})
${list(crossListed)}

## Unresolved or external pathway course names

These names appear on the guide's pathway pages but do not resolve to a
separate catalog entry (external courses, groups such as "Level 4 World
Language Courses", or entries with undefined markers). They are preserved
verbatim and displayed as-is.

${unresolved.map((p) => `### ${p.name} (${p.count})\n${list(p.names)}`).join("\n\n")}

## Known limitations (from the dataset)

${d.known_limitations.map((l) => `- ${l}`).join("\n")}
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, md);
console.log(`Audit written to ${path.relative(root, outFile)}`);
if (errors.length > 0) {
  console.error(`Schema problems found: ${errors.length}`);
  process.exit(1);
}
